services:
  test:
    build:
      context: .
      target: train
      dockerfile: rtdetrv2_pytorch/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '8gb'
    volumes:
      - .:/app
      - ${DS_MODEL_PATH:?error}:/models
      - ${DS_DATA_PATH:?error}:/data
    command: [
      "python", "rtdetrv2_pytorch/tools/train.py", 
      "--config", "rtdetrv2_pytorch/configs/rtdetrv2/rtdetrv2_r50vd_m_7x_coco.yml",
      "--resume", "/models/rtdetrv2_r50vd_m_7x_coco_ema.pth",
      "--device", "cuda:0",
      "--use-amp",
      "--output-dir", "/data/rtdetrv2_r18vd_120e_coco",
      "--test-only"
    ]
  train:
    build:
      context: .
      target: train
      dockerfile: rtdetrv2_pytorch/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '16gb'
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs visible
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Enable CUDA and nvidia-smi
      - WANDB_API_KEY=${WANDB_API_KEY:?please specify WANDB_API_KEY}
    volumes:
      - .:/app
      - ${DS_MODEL_PATH:?error}:/models
      - ${DS_DATA_PATH:?error}:/data
    command: [
      "python", "rtdetrv2_pytorch/tools/train.py", 
      "--config", "rtdetrv2_pytorch/configs/rtdetrv2/ds_rtdetrv2_m_coco.yml",
      "--tuning", "/models/rtdetrv2_r50vd_m_7x_coco_ema.pth",
      "--device", "cuda:0",
      "--use-amp",
      "--output-dir", "/models/ds_rtdetrv2_m_coco",
      "--update",
      "train_dataloader.dataset.img_folder=/data/data",
      "val_dataloader.dataset.img_folder=/data/data",
      "train_dataloader.dataset.ann_file=/data/train.json",
      "val_dataloader.dataset.ann_file=/data/val.json",
      # "train_dataloader.dataset.ann_file=/data/train_subsample.json",
      # "val_dataloader.dataset.ann_file=/data/val_small.json",
      "num_classes=1"
    ]

