task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/multi-gpu/RT-DETR_regnet_dla_support/rtdetr_pytorch/dataset/train2017
    ann_file: /home/multi-gpu/RT-DETR_regnet_dla_support/rtdetr_pytorch/dataset/annotations_trainval2017/annotations/instances_train2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 16
  num_workers: 8
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/multi-gpu/RT-DETR_regnet_dla_support/rtdetr_pytorch/dataset/val2017
    ann_file: /home/multi-gpu/RT-DETR_regnet_dla_support/rtdetr_pytorch/dataset/annotations_trainval2017/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 16
  num_workers: 8
  drop_last: False