task: detection

model: RTDETR
criterion: RTDETRCriterionv2
postprocessor: RTDETRPostProcessor


use_focal_loss: True
eval_spatial_size: [640, 640] # h w


RTDETR:
  backbone: PResNet
  encoder: MaskHybridEncoder
  decoder: MaskRTDETRTransformerv2


PResNet:
  depth: 50
  variant: d
  freeze_at: 0
  return_idx: [0, 1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: True


MaskHybridEncoder:
  in_channels: [256, 512, 1024, 2048]
  feat_strides: [4, 8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [3]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'

  # cross
  expansion: 1.0
  depth_mult: 1
  act: 'silu'

  # masks
  mask_feat_channels: [64, 64]
  num_prototypes: 32


MaskRTDETRTransformerv2:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3

  num_layers: 6
  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0

  eval_idx: -1

  num_points: [4, 4, 4]
  cross_attn_method: default
  query_select_method: default

  num_prototypes: 32
  mask_enhanced: True


RTDETRPostProcessor:
  num_top_queries: 100
  mask_threshold: 0.5


RTDETRCriterionv2:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_mask: 5, loss_dice: 5}
  losses: ['vfl', 'boxes', 'masks']
  alpha: 0.75
  gamma: 2.0
  num_sample_points: 12544
  oversample_ratio: 3.0
  important_sample_ratio: 0.75

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 4, cost_bbox: 5, cost_giou: 2, cost_mask: 5, cost_dice: 5}
    alpha: 0.25
    gamma: 2.0
    num_sample_points: 12544
