epoches: 20
val_step: 1
checkpoint_step: 1
save_optimizer: False
save_ema: False


train_dataloader: 
  dataset: 
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0, side_range: [1.0, 4.0], p: 0.5}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBox, min_size: 1}
        - {type: RandomHorizontalFlip}
        # - {type: ImgAug, config_path: "imgaug.json"}
        - {type: Resize, size: [640, 640]}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
        - {type: SanitizeBoundingBox, min_size: 1}
        - {type: ConvertBox, out_fmt: 'cxcywh', normalize: True}
  shuffle: True
  batch_size: 4
  num_workers: 4


val_dataloader:
  dataset: 
    transforms:
      ops: 
        - {type: Resize, size: [640, 640]}
        - {type: ToImageTensor}
        - {type: ConvertDtype}
  shuffle: False
  batch_size: 8
  num_workers: 4


optimizer:
  type: AdamW
  # params: 
  #   - 
  #     params: '^(?=.*backbone)(?=.*norm|bn).*$'
  #     weight_decay: 0.
  #     lr: 0.00001
  #   - 
  #     params: '^(?=.*backbone)(?!.*norm|bn).*$'
  #     lr: 0.00001
  #   - 
  #     params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
  #     weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

clip_max_norm: 0.1

lr_scheduler:
  type: MultiStepLR  # CosineAnnealingLR | OneCycleLR | LambdaLR
  milestones: [1000]
  gamma: 0.1

use_ema: True 
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000
