
__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]


output_dir: ./output/rtdetr_timm_resnet18_coco

RTDETR: 
  backbone: Timm

Timm:
  model_type: resnet18.fb_swsl_ig1b_ft_in1k

HybridEncoder:
  in_channels: [16,24,288]
  hidden_dim: 256
  expansion: 0.5
  depth_mult: 1.0
  eval_spatial_size: [640, 640]


RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 3
  num_denoising: 100
  # eval_spatial_size: [640, 640]



optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

