__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer_regnet.yml',
  './include/rtdetr_regnet.yml',
]

output_dir: ./output/rtdetr_regnet_6x_coco
