__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


eval_spatial_size: [512, 704]


PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformerv2:
  num_layers: 3


epoches: 36

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 32
  collate_fn:
    scales: [480, 512, 544, 576, 608, 640, 704, 704, 704, 704]
    stop_epoch: 32
  total_batch_size: 16

val_dataloader:
  dataset: 
    transforms:
      ops: 
        - {type: Resize, size: [512, 704]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   

wandb:
  project: 'platform-validation'
  group: rtdetr
  tags: ['ds-yolov4-full', 'rtdetr-v2', 'small','batch-16', '512x704']