__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

eval_spatial_size: [512, 704] # h, w
output_dir: ./output/rtdetrv2_r50vd_m_6x_coco


HybridEncoder:
  expansion: 0.5


RTDETRTransformerv2:
  eval_idx: 2 # use 3th decoder layer to eval


epoches: 36

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001


train_dataloader: 
  dataset:
    transforms:
      policy:
        epoch: 24
  collate_fn:
    scales: [480, 512, 544, 576, 608, 640, 704, 704, 704, 704]
    stop_epoch: 24
  total_batch_size: 8

val_dataloader:
  dataset: 
    transforms:
      ops: 
        - {type: Resize, size: [512, 704]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}   

wandb:
  project: 'platform-validation'
  group: rtdetr
  tags: ['ds-yolov4-full', 'rtdetr-v2', 'batch-8']
